/*
 * Copyright 2024-2026 Embabel Pty Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.embabel.agent.api.annotation.support

import com.embabel.common.core.types.Semver
import org.springframework.core.io.ClassPathResource
import org.springframework.core.io.support.PropertiesLoaderUtils
import java.io.IOException

/**
 * Resolve the version of the agent. The resolution order is
 *  - The version provided while defining the agent @Agent(version = "...")
 *  - The version provided in the Spring Boot build properties.
 *  - Semver.DEFAULT_VERSION as the final fallback.
 */

class AgentVersionResolver {
    // Generated by spring-boot-maven-plugin when it runs build-info goal during the build process.
    val BUILD_INFO_PROPERTIES_PATH = "META-INF/build-info.properties"
    // Load and cache the version once upon instantiation.
    private val cachedBuildVersion: String? by lazy {
        try {
            val resource = ClassPathResource(BUILD_INFO_PROPERTIES_PATH)
            if (resource.exists()) {
                val props = PropertiesLoaderUtils.loadProperties(resource)
                props.getProperty("build.version")?.takeIf { it.isNotBlank() }
            } else {
                null
            }
        } catch (e: IOException) {
            null
        }
    }

    fun resolveVersion(
        annotationVersion: String,
    ): String {
        // 1. If an explicit version is defined on the annotation, use it.
        if (annotationVersion != Semver.DEFAULT_VERSION) {
            return annotationVersion
        }

        // 2. Fall back to the version loaded once during startup/instantiation.
        cachedBuildVersion?.let { return it }

        // 3. Default fallback.
        return Semver.DEFAULT_VERSION
    }
}
